# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='cfedefaultshortcode', max_length=22),
            preserve_default=False,
        ),
    ]
